### PR TITLE
separate PLATFORMS_VALID for Matrix and Leia

### PR DESCRIPTION
**Pull request by AlwinEsch**
On Kodi Matrix the ios-armv7 no more supported.

This is another attempt to ask about a way to fix it.

With them I'm also not like, one thing is for Leia it is missing, the other is "tvos" only on Matrix.

What is the correct way to fix this problem?

Alternative to https://github.com/xbmc/pipeline-library/pull/8

### CODE REVIEW

**Comment by phunkyfish** [comment]
I’ve never written groovy but what about another dimension in PLATFORMS_VALID?

Then the list can be different for Leia and matrix?

**Comment by AlwinEsch** [comment]
That chould also a good way and to make them first https://github.com/xbmc/pipeline-library/blob/e2ec5cc7eb52e76749e5b75f9e53aa1764a8caa8/vars/buildPlugin.groovy#L68 and on places behind to take related list.

I can try to bring something as another attempt.

**Comment by phunkyfish** [comment]
So what’s the right way to do this @Rechi?

**Comment by AlwinEsch** [comment]
Is now changed to use a:
```groovy
	def version = addonParams.containsKey('version') && addonParams.version in VERSIONS_VALID ? addonParams.version : VERSIONS_VALID.keySet()[0]
	if (version == "Leia")
	{
		PLATFORMS_VALID = PLATFORMS_VALID_LEIA;
	}
	else if (version == "Matrix")
	{
		PLATFORMS_VALID = PLATFORMS_VALID_MATRIX;
	}
```
To select a wanted list.

**Comment by phunkyfish** [comment]
Nice 👍

**Comment by AlwinEsch** [comment]
@Rechi what you thing about now?

**Comment by Rechi** [comment]
So there will be a new valid platforms mapping for every new Kodi version, even if the supported platforms don't change?

**Comment by phunkyfish** [comment]
So it should be PLATFORMS_VALID_MASTER instead of PLATFORMS_VALID_MATRIX and just an else?

**Comment by AlwinEsch** [comment]
How is now?

**Comment by phunkyfish** [comment]
@Rechi can this go in now please?

We are doing serval API updates and never having Jenkins green increases the time it takes to get through it all. Having this in would really help.

**Comment by AlwinEsch** [comment]
@Rechi is it now OK?

Want to have them fixed!

**Comment by Rechi** [comment]
The PLATFORMS_VALID_MASTER variable doesn't fix anything for Kodi Matrix and N* having the same platforms once O* is development version and have different supported platforms.
Also master is not an unique version description over time and therefore must not be used.

**Comment by phunkyfish** [comment]
Would you prefer calling the variables: PLATFORMS_VALID_STABLE, PLATFORMS_VALID_DEVEL?

I'm sorry but I'm just not seeing how to protect this against future platform changes without further modifications at that time.

**Comment by phunkyfish** [comment]
Is this good to go in now @Rechi?

**Comment by AlwinEsch** [comment]
@rechi now tell what it should look like and set an example or bring yourself to fix the problem yourself!

This cannot be ignored for months as it affects all addons!

Also the right to remove me without any comment is not appropriate.

**Comment by AlwinEsch** [comment]
Here how I thought it look if Kodi N* is coming https://github.com/AlwinEsch/pipeline-library/commit/3033dbba63e4a17d9a4d65485be8ef76065a39ba

If nothing on the platform changed the old `PLATFORMS_VALID_CURRENT` can further used.

If now Kodi M* and N* are equal and Kodi O* have something else I thought for this:

```groovy
	def PLATFORMS_VALID_LEIA = [
		'android-armv7': 'android',
		'android-aarch64': 'android-arm64-v8a',
		'ios-armv7': 'ios',
		'ios-aarch64': 'ios',
		'osx-x86_64': 'osx64',
		'ubuntu-ppa': 'linux',
		'windows-i686': 'windows/win32',
		'windows-x86_64': 'windows/x64'
	]
	def PLATFORMS_VALID_MATRIX_NEMESIS = [
		'android-armv7': 'android',
		'android-aarch64': 'android-arm64-v8a',
		'tvos-aarch64': 'tvos',
		'ios-aarch64': 'ios',
		'osx-x86_64': 'osx64',
		'ubuntu-ppa': 'linux',
		'windows-i686': 'windows/win32',
		'windows-x86_64': 'windows/x64'
	]
	def PLATFORMS_VALID_CURRENT = [
		'android-x86': 'androidx86',
		'android-x86_64' : 'android-x86_64',
		'android-armv7': 'android',
		'android-aarch64': 'android-arm64-v8a',
		'tvos-aarch64': 'tvos',
		'ios-aarch64': 'ios',
		'osx-x86_64': 'osx64',
		'ubuntu-ppa': 'linux',
		'windows-i686': 'windows/win32',
		'windows-x86_64': 'windows/x64',
		'new-pseudo-os-x86_128': 'pseudo-os-x86_128'
	]

...

	def version = addonParams.version
	if (version == "Leia")
	{
		PLATFORMS_VALID = PLATFORMS_VALID_LEIA
	}
	else if (version == "Matrix" || version == "Nemesis")
	{
		PLATFORMS_VALID = PLATFORMS_VALID_MATRIX_NEMESIS
	}
	else
	{
		PLATFORMS_VALID = PLATFORMS_VALID_CURRENT
	}
```

**Comment by lrusak** [comment]
@AlwinEsch thanks for all your work on this and getting our binary-addons pipeline building again!

**Pull request merged**
