### PR TITLE
publish: call script on server instead of doing it inline

### PR DESCRIPTION
**Pull request by wsnipex**
fix uploading to new mirror servers

### CODE REVIEW

**Review by lrusak — APPROVED** [review]
LGTM

where is the `move_addons.sh` script stored?

**Comment by wsnipex** [comment]
/usr/local/bin/move_addons.sh on the mirror servers ;)

**Comment by howie-f** [comment]
would be a good idea to store it here in the repo, too 🙂

**Comment by lrusak** [comment]
> /usr/local/bin/move_addons.sh on the mirror servers ;)

Would be nice to have that somewhere in version control

**Comment by wsnipex** [comment]
we can put it anywhere you like, but I prefer not in here.
But let's first verify it works and get the uploads going again, shall we?

**Pull request merged**
